### ISSUE TITLE
Is it pin compatible re. Uno HATs etc?

### ISSUE THREAD

**Issue by Kagee** [GlowDuino/GlowDuino#1]
Is it pin compatible with Uno HATs etc? Is it is/is not, it would be smart to mention here and on Tindie.

Btw, your Tindie listing says "prgoramable".

**Comment by GlowDuino** [comment]
> Is it pin compatible with Uno HATs etc? Is it is/is not, it would be smart to mention here and on Tindie.
> 
> Btw, your Tindie listing says "prgoramable".

Hi!

Yes, the GlowDuino Uno board is pin-compatible with the original Arduino Uno. The extra pins that the GlowDuino board has, are on the left side of the board, where general HATs cannot plug into. The pins that these HATs use are in the same place, so you can use them on the GlowDuino boards as well.

Thank you for pointing out the typo, unfortunately, it happens sometimes with the amount of text we are working with.

If you have any other questions, please feel free to ask.

-Levente

**Comment by Kagee** [comment]
"programmable", not "programable" 😉

I see you mention "while being backward compatible with existing designs." on Tindie, but i suggest you also include something like the answer above on the listings page :)
